DROP USER crm

SELECT SCHEMA_NAME, 
    SCHEMA_OWNER
FROM INFORMATION_SCHEMA.schemata
WHERE SCHEMA_OWNER = 'crm';

SELECT SCHEMA_NAME, 
    SCHEMA_OWNER
FROM INFORMATION_SCHEMA.schemata
WHERE SCHEMA_OWNER = 'dbo';

ALTER AUTHORIZATION ON SCHEMA::db_datareader TO dbo
ALTER AUTHORIZATION ON SCHEMA::db_datawriter TO dbo


